const jsTranslations = {
    'poem_alpha_a_title': `A harfi uchun she'r`,
    'poem_alpha_a_subtitle': `Alifbo she'rlari`,
    'poem_alpha_a_body': `Ahil asalarilar<br>Azonlab tushar ishga<br>Atrof dala, bogʻlardan<br>Asal yigʻishar qishga<br>Ayiq boʻlsa, meshqorin<br>Asallarni yer, borin.<br>Arilar xafa gʻoyat,<br>Axir' bormi adolat?!`,
    'poem_alpha_b_title': `B harfi uchun she'r`,
    'poem_alpha_b_subtitle': `Alifbo she'rlari`,
    'poem_alpha_b_body': `Baliq boyvuchcha, desam,<br>Bekor gap, dema hecham.<br>Boq oʻzing, ana oʻrtoq,<br>Badani xoʻp yaltiroq.<br>Boshdan-oyoq tanga u,<br>Bas, boyvuchcha yanga u.`,
    'poem_alpha_d_title': `D harfi uchun she'r`,
    'poem_alpha_d_subtitle': `Alifbo she'rlari`,
    'poem_alpha_d_body': `Delfin mohir dengizchi,<br>Dono, aqlli biram<br>Dengizda choʻksa birov<br>Darrov beradi yordam.`,
    'poem_alpha_e_title': `E harfi uchun she'r`,
    'poem_alpha_e_subtitle': `Alifbo she'rlari`,
    'poem_alpha_e_body': `Etikdoʻz Echki eski<br>Etiklarni rostladi.<br>Eplab, qolipga tortib,<br>Eshakvoyga mosladi.`,
    'poem_alpha_f_title': `F harfi uchun she'r`,
    'poem_alpha_f_subtitle': `Alifbo she'rlari`,
    'poem_alpha_f_body': `Farrosh Fill xola, qarang,<br>Tozalabdi har yoqni.<br>Topmaysiz hech yerda chang,<br>Artib kiring oyoqni.<br>Fayzli, fusunkor boʻlib,<br>Yashnab turar hamma yoq.<br>Farroshlar mehnatini<br>Qadrlang siz ey oʻrtoq!`,
    'poem_alpha_g_title': `G harfi uchun she'r`,
    'poem_alpha_g_subtitle': `Alifbo she'rlari`,
    'poem_alpha_g_body': `Gimnastikachi--<br>Gavdali, durkun<br>Gardani yoʻgʻon<br>Gorilla maymun.<br>Gap yoʻq mashqiga,<br>Bajarar chaqqon,<br>Olqishlar olib,<br>Hammaga yoqqan.`,
    'poem_alpha_h_title': `H harfi uchun she'r`,
    'poem_alpha_h_subtitle': `Alifbo she'rlari`,
    'poem_alpha_h_body': `Hakka harbiy xizmatda,<br>Himoyachi zoʻr posbon!<br>Havodan oʻtmas pashsha,<br>Hatlolmas yerdan sichqon.`,
    'poem_alpha_i_title': `I harfi uchun she'r`,
    'poem_alpha_i_subtitle': `Alifbo she'rlari`,
    'poem_alpha_i_body': `It ishonchli izquvar,<br>Ishini yaxshi bilar.<br>Ishkal qilsa kim-birov,<br>Izini olib darrov,<br>Izlab-izlab topadi,<br>Irillaydi qopadi!`,
    'poem_alpha_j_title': `J harfi uchun she'r`,
    'poem_alpha_j_subtitle': `Alifbo she'rlari`,
    'poem_alpha_j_body': `Jarroh Jayra<br>Ja zoʻr-da.<br>Kasallarga<br>Gʻamxoʻrda<br>Sekin tiqar ninasin.<br>Ishonmagan sinasin.`,
    'poem_alpha_k_title': `K harfi uchun she'r`,
    'poem_alpha_k_subtitle': `Alifbo she'rlari`,
    'poem_alpha_k_body': `Kalamushvoy kemirar,<br>Kundan-kunga semirar.<br>Boshqa kasb kori yoʻq,<br>Andishasi ori yo'q.`,
    'poem_alpha_l_title': `L harfi uchun she'r`,
    'poem_alpha_l_subtitle': `Alifbo she'rlari`,
    'poem_alpha_l_body': `Lofchi laylak lof urar,<br>Laqma, laqqa baqaga.<br>Soʻng cho'qib shartta yutar,<br>Dars bu bola-chaqaga.`,
    'poem_alpha_m_title': `M harfi uchun she'r`,
    'poem_alpha_m_subtitle': `Alifbo she'rlari`,
    'poem_alpha_m_body': `Maymun bilan Mosh mitti<br>Masxaraboz oʻyinchi.<br>Maydonda mashq qilmoqda,<br>Mana, siz ham koʻring-chi:<br>Maymunni mashinaday<br>Minib, haydamoqchi Mosh.<br>"Mashina"-chi, miq etmas,<br>Tormozda-da, na iloj...`,
    'poem_alpha_n_title': `N harfi uchun she'r`,
    'poem_alpha_n_subtitle': `Alifbo she'rlari`,
    'poem_alpha_n_body': `Ninachixon raqqosa<br>Nozik, navnihol rosa.<br>Nazar soling, naqadar<br>Nafis raqsga tushar.`,
    'poem_alpha_o_title': `O harfi uchun she'r`,
    'poem_alpha_o_subtitle': `Alifbo she'rlari`,
    'poem_alpha_o_body': `Ot kasbi -ishchi,<br>Omborchi, yukchi,<br>Ortib don-dunni,<br>Oppoq tuz, unni,<br>Olib yeladi, olib keladi.`,
    'poem_alpha_p_title': `P harfi uchun she'r`,
    'poem_alpha_p_subtitle': `Alifbo she'rlari`,
    'poem_alpha_p_body': `Pingvin xola pazanda,<br>Piyoz sabzi qozonda.<br>Peshin palov pishsin deb<br>Ish boshlagan azonda`,
    'poem_alpha_q_title': `Q harfi uchun she'r`,
    'poem_alpha_q_subtitle': `Alifbo she'rlari`,
    'poem_alpha_q_body': `Qaldirgʻochga qoyil-a,<br>Qarang, qanday quruvchi.<br>Quribdi loydan uya,<br>Qotiribdi, koʻring-chi.<br>Qiyin ishmi shuyam deb,<br>Qora qargʻa gap qotar.<br>Oʻzi qurgan in esa,<br>Shamolda qulab yotar.`,
    'poem_alpha_r_title': `R harfi uchun she'r`,
    'poem_alpha_r_subtitle': `Alifbo she'rlari`,
    'poem_alpha_r_body': `Rassom Buzoq<br>Rasm solar.<br>Quyon qoʻrqib<br>Razm solar.<br>Rasmlarning<br>zo'ri-da u,<br>Rosa katta<br>Boʻrida u!`,
    'poem_alpha_s_title': `S harfi uchun she'r`,
    'poem_alpha_s_subtitle': `Alifbo she'rlari`,
    'poem_alpha_s_body': `Sa'vaxon-suxandon,<br>Soʻzlari biyron-biyron.<br>Soling quloq, qanday soz,<br>Sehrli, sohir ovoz!`,
};